### ISSUE TITLE
some funk re-upping the box after first build

### ISSUE THREAD

**Issue by pirog** [kalamuna/kalastack#27]
i have traced this issue to some sort of permissions error that seems to happen when the box tries to establish network connections on a start. it seems to be coming from the new user module.

**Comment by pirog** [comment]
might be a syntax error in one of the files.

**Comment by pirog** [comment]
/Applications/Vagrant/embedded/gems/gems/net-scp-1.1.0/lib/net/scp.rb:385:in `await_response_state':  (RuntimeError)
    from /Applications/Vagrant/embedded/gems/gems/net-scp-1.1.0/lib/net/scp.rb:356:in`block (3 levels) in start_command'
    from /Applications/Vagrant/embedded/gems/gems/net-ssh-2.6.6/lib/net/ssh/connection/channel.rb:311:in `call'
    from /Applications/Vagrant/embedded/gems/gems/net-ssh-2.6.6/lib/net/ssh/connection/channel.rb:311:in`process'
    from /Applications/Vagrant/embedded/gems/gems/net-ssh-2.6.6/lib/net/ssh/connection/session.rb:214:in `block in preprocess'
    from /Applications/Vagrant/embedded/gems/gems/net-ssh-2.6.6/lib/net/ssh/connection/session.rb:214:in`each'
    from /Applications/Vagrant/embedded/gems/gems/net-ssh-2.6.6/lib/net/ssh/connection/session.rb:214:in `preprocess'
    from /Applications/Vagrant/embedded/gems/gems/net-ssh-2.6.6/lib/net/ssh/connection/session.rb:197:in`process'
    from /Applications/Vagrant/embedded/gems/gems/net-ssh-2.6.6/lib/net/ssh/connection/session.rb:161:in `block in loop'
    from /Applications/Vagrant/embedded/gems/gems/net-ssh-2.6.6/lib/net/ssh/connection/session.rb:161:in`loop'
    from /Applications/Vagrant/embedded/gems/gems/net-ssh-2.6.6/lib/net/ssh/connection/session.rb:161:in `loop'
    from /Applications/Vagrant/embedded/gems/gems/net-ssh-2.6.6/lib/net/ssh/connection/channel.rb:269:in`wait'
    from /Applications/Vagrant/embedded/gems/gems/net-scp-1.1.0/lib/net/scp.rb:279:in `upload!'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.2/plugins/communicators/ssh/communicator.rb:105:in`block in upload'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.2/plugins/communicators/ssh/communicator.rb:309:in `block in scp_connect'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.2/plugins/communicators/ssh/communicator.rb:141:in`connect'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.2/plugins/communicators/ssh/communicator.rb:307:in `scp_connect'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.2/plugins/communicators/ssh/communicator.rb:99:in`upload'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.2/plugins/guests/debian/guest.rb:42:in `configure_networks'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.2/plugins/providers/virtualbox/action/network.rb:115:in`call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.2/lib/vagrant/action/warden.rb:34:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.2/plugins/providers/virtualbox/action/clear_network_interfaces.rb:26:in`call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.2/lib/vagrant/action/warden.rb:34:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.2/plugins/providers/virtualbox/action/share_folders.rb:20:in`call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.2/lib/vagrant/action/warden.rb:34:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.2/plugins/providers/virtualbox/action/clear_shared_folders.rb:12:in`call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.2/lib/vagrant/action/warden.rb:34:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.2/plugins/providers/virtualbox/action/prepare_nfs_settings.rb:11:in`call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.2/lib/vagrant/action/warden.rb:34:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.2/lib/vagrant/action/builtin/nfs.rb:28:in`call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.2/lib/vagrant/action/warden.rb:34:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.2/plugins/providers/virtualbox/action/prune_nfs_exports.rb:15:in`call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.2/lib/vagrant/action/warden.rb:34:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.2/lib/vagrant/action/builtin/handle_forwarded_port_collisions.rb:101:in`call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.2/lib/vagrant/action/warden.rb:34:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.2/plugins/providers/virtualbox/action/prepare_forwarded_port_collision_params.rb:30:in`call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.2/lib/vagrant/action/warden.rb:34:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.2/lib/vagrant/action/builtin/env_set.rb:19:in`call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.2/lib/vagrant/action/warden.rb:34:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.2/lib/vagrant/action/builtin/provision.rb:45:in`call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.2/lib/vagrant/action/warden.rb:34:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.2/plugins/providers/virtualbox/action/clear_forwarded_ports.rb:13:in`call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.2/lib/vagrant/action/warden.rb:34:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.2/plugins/providers/virtualbox/action/set_name.rb:35:in`call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.2/lib/vagrant/action/warden.rb:34:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.2/plugins/providers/virtualbox/action/clean_machine_folder.rb:17:in`call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.2/lib/vagrant/action/warden.rb:34:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.2/plugins/providers/virtualbox/action/check_accessible.rb:18:in`call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.2/lib/vagrant/action/warden.rb:34:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.2/lib/vagrant/action/runner.rb:61:in`block in run'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.2/lib/vagrant/util/busy.rb:19:in `busy'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.2/lib/vagrant/action/runner.rb:61:in`run'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.2/lib/vagrant/action/builtin/call.rb:51:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.2/lib/vagrant/action/warden.rb:34:in`call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.2/lib/vagrant/action/runner.rb:61:in `block in run'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.2/lib/vagrant/util/busy.rb:19:in`busy'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.2/lib/vagrant/action/runner.rb:61:in `run'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.2/lib/vagrant/action/builtin/call.rb:51:in`call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.2/lib/vagrant/action/warden.rb:34:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.2/lib/vagrant/action/runner.rb:61:in`block in run'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.2/lib/vagrant/util/busy.rb:19:in `busy'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.2/lib/vagrant/action/runner.rb:61:in`run'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.2/lib/vagrant/action/builtin/call.rb:51:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.2/lib/vagrant/action/warden.rb:34:in`call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.2/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.2/lib/vagrant/action/warden.rb:34:in`call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.2/plugins/providers/virtualbox/action/check_virtualbox.rb:17:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.2/lib/vagrant/action/warden.rb:34:in`call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.2/lib/vagrant/action/builtin/call.rb:57:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.2/lib/vagrant/action/warden.rb:34:in`call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.2/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.2/lib/vagrant/action/warden.rb:34:in`call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.2/plugins/providers/virtualbox/action/check_virtualbox.rb:17:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.2/lib/vagrant/action/warden.rb:34:in`call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.2/lib/vagrant/action/builder.rb:109:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.2/lib/vagrant/action/runner.rb:61:in`block in run'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.2/lib/vagrant/util/busy.rb:19:in `busy'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.2/lib/vagrant/action/runner.rb:61:in`run'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.2/lib/vagrant/machine.rb:129:in `action'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.2/plugins/commands/up/command.rb:37:in`block in execute'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.2/lib/vagrant/plugin/v2/command.rb:182:in `block in with_target_vms'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.2/lib/vagrant/plugin/v2/command.rb:180:in`each'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.2/lib/vagrant/plugin/v2/command.rb:180:in `with_target_vms'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.2/plugins/commands/up/command.rb:32:in`execute'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.2/lib/vagrant/cli.rb:46:in `execute'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.2/lib/vagrant/environment.rb:406:in`cli'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.2/bin/vagrant:60:in `<top (required)>'
    from /Applications/Vagrant/bin/../embedded/gems/bin/vagrant:23:in`load'
    from /Applications/Vagrant/bin/../embedded/gems/bin/vagrant:23:in `<main>'

**Comment by pirog** [comment]
looks like either .exports or .aliases was causing this. going to remove for now and will reimplement later.
